name: 开始每日签到

on:
  workflow_dispatch:
  schedule:
    # UTC 1点30分(北京时间 9点30分)
    - cron: 30 1 * * *
  # 标星时触发工作流程
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run checkin
        run: |
          python3 glados.py
        env: 
          GLADOS_COOKIE: "koa:sess=eyJ1c2VySWQiOjM5NDEzOCwiX2V4cGlyZSI6MTcyMzkwODIwNzg0NCwiX21heEFnZSI6MjU5MjAwMDAwMDB9; koa:sess.sig=qfyFckcDnJsc5KT1U2UoRrH8kvA; _gid=GA1.2.1105614818.1698191348; _gat_gtag_UA_104464600_2=1; _ga=GA1.1.889077256.1697988184; _ga_CZFVKMNT9J=GS1.1.1698191348.2.1.1698191377.0.0.0"
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      - uses: gautamkrishnar/keepalive-workflow@master  
